# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/2e764e78-2d70-4507-a782-5b67e2a11d66/transcription
Content-Type: application/json

{
    "prompt": "Timer de um minuto"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "3dab0797-7aef-4462-82f7-f1e396225608",
    "temperature": 0.5,
    "prompt": "Gere um resumo sucinto da trasncrição do vídeo informada a seguir: '''{transcription}''' "
}